### PR TITLE
Add roll counters to Need/Greed frames

### PR DESCRIPTION
**Pull request by Toludin**
Added:
- Roll counters for group mates on N/G/P buttons for each loot window.
- Track all items you've rolled on in a blacklist, so they don't "pop
back" for a second after you roll (occasional bug)

Issues:
- Since we're only passed an Item when a roll occurs (and it has no
LootId), it's impossible to know which of two duplicate items the user
might have wanted to roll on. Right now, their rolls shows on both
frames - so one user hitting Need on one item and Pass on the other
would show 1 Need and 1 Pass on both of those duplicate items to the
player. There are alternatives to this (including grouping duplicate
items into one roll frame), but I think this may be the best way to
display this info. I believe this is also only true for 'basic' items, not actual loot
people would more likely be rolling on.

### CODE REVIEW

**Comment by adamjedlicka** [comment]
Nice, I will test it after the raid. I think you don't need to worry about duplicate rolls, because there isn't many ppl which will need on one stack of modules and greed on the second.

**Comment by Toludin** [comment]
Let's say you have a group of 5. Right now, if 2 of an item that shares the same Item table drops, and all 4 other people hit 'Need' on both items, you would see 8 Need rolls on both item windows.

This will be resolved in the future when we change how items are stored. Even without that, as soon as I add the option to show who rolled on each item, we can use that to check if we're adding two rolls for one person on an item (and then know to skip that increment).

Let me know if you see any of this 'additional rolls' behavior on items people will actually roll for. I was testing on low level mobs, putting the loot threshold very low (so I would roll on Cloth Scraps and such). I'm not sure if higher quality/level items will share Item tables, too - but I imagine Runes and such might.

**Comment by Toludin** [comment]
Just going to implement that now, actually.

**Comment by adamjedlicka** [comment]
Ok then I wait with testing.

**Comment by Toludin** [comment]
Just ran a test with the new version in Malgrave, it worked pretty well. One time it showed one item with 6 rolls (obviously too many), but I'm not sure if it's going to be 100% (at least not without a more robust rewrite...and even then, nothing in this game is 100%!)

One issue I do need to address is getting the player's name on load. Need to delay that - sometimes generates an error on game load.

**Comment by Toludin** [comment]
Added a Need 'window' when you can't roll Need, so that I have something to display the Need rolls onto (otherwise you can't see who might be rolling Need, if you can't yourself). Let me know what you think of this, and please change if you don't like it - this is your addon and I want to make sure it's still in line with your style.

I've been testing this for several days now. Haven't seen any major issues. Occasionally still seeing one item show more rolls than possible (I swear I've seen a 6 at times in a party), but I can't reliably reproduce any problems, in raids or groups.

Not sure if you've been playing with it at all, but have you seen any problems? I think it's ready for larger deployment at this point.

**Comment by adamjedlicka** [comment]
I haven't tried it yet. I'm preparing for entry tests for university so I dont play at all lately, but I will try to test it and release it as soon as possible.

**Comment by Toludin** [comment]
Gotcha. Good luck!

**Comment by adamjedlicka** [comment]
Thansk :)

**Pull request merged**
