### PR TITLE
Nameplates - TapCast v2, IA dynamic sprites, guild color & tweaks (+media)

### PR DESCRIPTION
**Pull request by veex-ua**
Default nameplate style is changed. Default texture is now "Edge". Nameplate is now slightly higher above unit. Healthbar height slightly increased. Castbar height slightly increased and is not overlapped with castbar text and castbar text is centered below castbar to improve readability.
Default nameplate IA style is now "Carbine". Current default "ForgeUI_shield" is too ugly imo. 
Player nameplate: Healthbar/Castbar visibility is set to [In Combat] by default (this is standard for most MMO's)
Buff-borders is now dark. Maybe it's just me but current green borders are not fitting into default dark theme. Even when using light colors theme for unit frames etc dark borders looks a lot better imo.

### CODE REVIEW

**Comment by veex-ua** [comment]
Think I'll leave merging pull requests to you unless it's some very minimal changes.

**Comment by adamjedlicka** [comment]
Merging pull requests leave on me for now.
I will start using branches too. When multiple ppl commit to one branch at the same time and then push to remote git gets stuck and it's not easy to resolve. That's the main reason for using branches and pull requests.

**Comment by veex-ua** [comment]
Alright. Just letting you know that I'm not gonna mess with master branch at all and all of my changes are going to be via pull-requests. So up to you how you want to work, with master or with branches.

**Comment by veex-ua** [comment]
Got some feedback on tap casting, so far everything works fine. I have some tweaks to tap casting and fix for #144 so keep this open for now.

**Comment by adamjedlicka** [comment]
Ok. Just say when its ready to be merged.

**Comment by veex-ua** [comment]
So I've run in to my first merge conflict and I can't really figure out why it can't merge these. Before my lattest commit to 0.53b merging was fine and now it fails at merge with rewrite/addon-init. Help :smile:

**Comment by veex-ua** [comment]
nvm, managed to merge them in the end. Conflict was in formating. Does formating must be exactly same when merging? I thought it will ignore whitespaces completely

**Comment by adamjedlicka** [comment]
Git uses simple diff so any change in the line (whitespace, enter at the end, ...) is same as changing whole line completely. But solving conflicts is easy. Just if you do merge and git says there are conflicts, opne the files with conflicts, rewrite the conflicted code how you want, and commit. Thats it.

**Comment by veex-ua** [comment]
Yea, this branch conflict is also very easy to solve. Anyways, gonna give it a final test today in raid, also asked bunch of guildmates to download it and test in raid. Hopefully everything will go smooth.

**Comment by adamjedlicka** [comment]
Ok. Don't think so extensive testing is neccesarry for these "simple" cahnges, but doesn't hurt anyone neither :)

**Comment by veex-ua** [comment]
So everything went fine, can be merged. Bad news is that people stuck on me they want player castbar to work same as nameplate castbar does now.

**Comment by adamjedlicka** [comment]
If you want you can redo it too.

**Pull request merged**
