### PR TITLE
Disable tapCast for spellslingers and short names tweak

### PR DESCRIPTION
**Pull request by veex-ua**
Spellslingers casting system turns out to be rather complex. I'll see if I can fix that. Disabled for now.
closes ForgeUI/ForgeUI#261, closes ForgeUI/ForgeUI#262

### CODE REVIEW

**Comment by Jeffroiscool** [comment]
Thx, I downloaded the file for now so I can continue raiding :D

**Comment by Jeffroiscool** [comment]
The issue actually doesn't seem to be happening for Slingers only. 
Friend of mine has the issues on his Esper, walking around in BG's and Thayd and usually when he's casting something. The exact same error as I've been getting (doesn't trigger on trying stuff on a dummy though).

Maybe disable the whole tapcast function for now, now he has to reloadui like everytime it happens (which can be every 30s).

**Comment by adamjedlicka** [comment]
Does it happen if he disables tapcast on Nameplates?

**Comment by Jeffroiscool** [comment]
I've checked to see if there's an option for this but I can't find it.

**Comment by adamjedlicka** [comment]
Nevermind. Then try settings Cast bar to "Never" for players nameplate. But this is kind of unviable solution in the long run.

**Comment by veex-ua** [comment]
I have a fix ready for this issue, but I want to test it a bit more. Will pull-request it today.

**Comment by adamjedlicka** [comment]
Cool

**Comment by veex-ua** [comment]
I pushed changes into a new branch 0.53b (https://github.com/ForgeUI/ForgeUI/tree/0.53b) would like you guys to check it out and voice your opinions.

Also, as I am fairly new to Git in general have couple of questions:

What is the correct way to propose changes that I don't want yet to push into master branch? Should I create pull-request to merge with master and you firstly merge it locally to see how it works and only then accept pull-request? Or should I just push in to seperate branch as I did now so anyone can download zip of the branch to test changes? Second solution make more sense to me so I went with it for now.

**Comment by adamjedlicka** [comment]
If you create a new branch and push that branch to origin (GitHub) everyone can check it out, download ito, contribute to it, etc... with or without pull request. So if you want you can literally spam-create new branches with new features/fixes to let other ppl test it and eventualy merge it into master. Pull request is used when you are fairly certain this should be merged to master.

**Comment by veex-ua** [comment]
So if I understand that correctly what I did now (new branch push) is the proper way.

**Comment by adamjedlicka** [comment]
Yes

**Comment by adamjedlicka** [comment]
Now when I'm thinking about it, it is maybe better to create pull request earlier (for example right now for your new branch), because you can easilly discuss it there. Atm there is no dedicated place to discuss changes in that branch, except code comments, but those should be used for different purpouse.

**Comment by adamjedlicka** [comment]
Yup just tested it. If you create a pull request and then commit and push new changes that same pull request gets updated with those changes. So yeah, just create pull request when there are some changes which can be discussed.

**Comment by veex-ua** [comment]
Oh, "Discussing changes" topic was actually a second question I wanted to ask and forgot. Was wondering if there is any live-chat feature or something to communicate outside of code comments.

Also you asked for skype or discord contacts. I have to check if I can find my logins to these as I am not activly using either of them. Might want to add that being non native english speaker I can't really communicate via voice chats, my language is that bad... typing skills is a bit better though.

**Comment by adamjedlicka** [comment]
No github doesnt provide any live chat.

About skype/discord. I didnt mean it for voice communication but for instant messaging. If you are not using any of those regurarly then maybe something else? Or e-mail? Just something for private discussion, because github doesnt support it. If you want to use e-mail, just use my e-mail address adajedlicka@gmail.com

**Comment by veex-ua** [comment]
Yeah I guess email will work just fine for now. My is bosston86@hotmail.com in case you'll need it. Will check discord and how it works, maybe shall use it if it's handy.

Also it's a shame that such huge service doesn't have any instant messaging system.

**Pull request merged**
