### PR TITLE
Rewrite addon/module innitialization process

### PR DESCRIPTION
**Pull request by adamjedlicka**
I'm gonna need some testing on this one to make sure it works 100% for everyone. It is "small" tweak to allow more controlled loading of addons in proper order. Basically for the end user nothing should be different from previous versions.

Also try to test it with this addon: https://github.com/ForgeUI/ForgeUI_ActionBarsExt

### CODE REVIEW

**Comment by veex-ua** [comment]
Will give it a go today when I'll get back home. Also what with all these whitespaces add/removing. You really need an editor with trim on save function :smile:

**Comment by adamjedlicka** [comment]
I'm using Visual Studio code which has plugin for formatting lua code but unfortunatelly it does only space formating (not tabulation) which sucks. If you know some lua code format which can do tabulation and is preferably little bit configurable (width of line, ...) let me know.

**Comment by veex-ua** [comment]
Notepad ++
Auto formatting, configurable tab indent, code completion, function list, trim on save and probably more that I don't even know about.

**Comment by adamjedlicka** [comment]
Yeah notepad++ is good but unfortunatelly doesn't have version for linux (which is must have for me) and I'm to used for VS Code to switch editors.

**Comment by Jeffroiscool** [comment]
Well any editor is fine as long as you can get it to work the way you want.
Zod recommended Atom to me but I haven't gotted around using it that much yet.

I'm still too used to Notepad++ :P

**Comment by veex-ua** [comment]
Any idea why when I download zip of this branch ..ForgeUI\libs\ forlder has only empty folders? Like "GeminiDB", "GeminiHook" and rest of them are empty?! Was going to post all of these error addon throwed at me but then realized it can't load files because they don't exist.

**Comment by veex-ua** [comment]
wrong button..

**Comment by adamjedlicka** [comment]
@veex-ua This is because those folders (libs) are now git submodules, so they should be empty. When you are cloning the repo you have to use --recurse flag to clone it with modules.

`git clone --recursive https://github.com/ForgeUI/ForgeUI.git`

**Comment by veex-ua** [comment]
ok. just to make sure I'm doing everything correctly:
cloned > checkout addon/rewrite-init branch > made sure that code has latests commits these branch has on remote > copied folders to game addons folder > everything launched fine, no errors.

gonna test https://github.com/ForgeUI/ForgeUI_ActionBarsExt now

**Comment by adamjedlicka** [comment]
It's even easier.

1) Clone if you don't have ForgeUI at all or you want to create new copy (clone is basically download). Clone will also everytime downloads latests commits
2) If you already have ForgeUI cloned and want to make sure its up to date use git pull . It will download lastests commits and branches.
3) Because of how .gitignore is set up you can copy cloned ForgeUI repo right to the addons folder. Like this: [http://i.imgur.com/VB3nJy2.png](http://i.imgur.com/VB3nJy2.png) (with .git direcotry and everything). Now you can just work in that addon folder without worrying. Commiting code, checking out branches, uploading to GitHub. Every other addons gets fildered out, so you don't have to worry about anything.

**Comment by veex-ua** [comment]
Ty for tips. still have a lot to learn about Git. So far everything works flawlessly for me including ActionBarsExt. I didn't find how to setup buttons custom positions though but I guess it's not implemented yet.

**Comment by adamjedlicka** [comment]
Buttons custom positions? In the left menu of ForgeUI is new button Action bars ext, click on it and create new bar. After that click on red plus next to Action bars ext button and customize your newly created bar.

**Comment by veex-ua** [comment]
Ahhh. so I just got it how you intend it to work... So basically if I want custom button I create new action bar for it and drag it wherever I want. What I did is created new bar, made it, say 6 buttons row and was looking how to manually set position of each button in this row.

**Comment by adamjedlicka** [comment]
Yeah. Its just basic action bar with customizable buttons. Didn't took much time to create, its quite easy to setup properly imho and if you want solo buttons, you can just create multiple bars with only one button.

**Comment by veex-ua** [comment]
Yeap. Was expecting it to work as it was in v0.48 etc where you drag each button in action bar. This is actually much better solution.

**Comment by veex-ua** [comment]
Another Git question:

I want to create new branch and merge all of the currently opened pull-requests with it to test how these changes are working together. It should be possible, right? maybe some tips :smile:

**Comment by adamjedlicka** [comment]
Yeah. You dont even need to create pull request or publish that branch on Github. Just checkout master, branch it (git branch new-branch), git checkout that new branch and then you can start merging. git merge target-branch . If you use this, target branch gets merget to the current branch. After you are done with it, you can just delete it via git branch -d

**Pull request merged**
