### PR TITLE
Nameplates - Healing absorption indicator

### PR DESCRIPTION
**Pull request by veex-ua**

### CODE REVIEW

**Comment by adamjedlicka** [comment]
Awesome. Could you please send me a screenshot? I'm on vacation right now and I would like to see how it looks.

**Comment by veex-ua** [comment]
There it is http://imgur.com/yZKaTwl

It is reversed progress bar so it depletes towards right border.

**Comment by veex-ua** [comment]
Also keep in mind this is for PTR only as API hasn't been updated yet on live.

**Comment by adamjedlicka** [comment]
Looks awesome. Ill contact few ppl for testing. By looking at the code it looks like it will work if GetHealingAbsorptionValue is the proper method (which probabbly is).

BTW release of RMT is on 17th of August, right?

**Comment by veex-ua** [comment]
Yea, 17th was announced as release date.

**Pull request merged**
